ci(*): switch pre-release to manual trigger
Added a check to ensure only proper release candidate branches can be published. This change provides more explicit control over when release candidates are generated.

diff --git a/.github/workflows/pre-release-package.yml b/.github/workflows/pre-release-package.yml
--- a/.github/workflows/pre-release-package.yml
+++ b/.github/workflows/pre-release-package.yml
@@ -1,10 +1,7 @@
 name: Intuiface-CDK Pre-Release Package
 
 on:
-  pull_request:
-    types: [opened, synchronize]
-    branches:
-      - 'release-please--branches--master**'
+  workflow_dispatch:
 
 jobs:
 
@@ -15,6 +12,13 @@ jobs:
       contents: read
       id-token: write
     steps:
+      - name: Validate branch name
+        run: |
+          if [[ "${{ github.ref_name }}" != release-please--branches--master* ]]; then
+            echo "Branch '${{ github.ref_name }}' can't be pre-released. Only RC branch from release-please can be published."
+            exit 1
+          fi
+
       - uses: actions/checkout@v6
 
       - uses: actions/setup-node@v6
